apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
    name: testapp-eks
    region: ap-south-1

nodeGroups:
    - name: ng-101
      instanceType: t2.small
      desiredCapacity: 3
      ssh: 
        publicKeyName: kube
