apiVersion: apps/v1
kind: Deployment
metadata:
  name: knote
spec:
  replicas: 2
  selector:
    matchLabels:
      app: knote
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: knote
    spec:
      containers:
        - name: app
          image: 096002618444.dkr.ecr.ap-south-1.amazonaws.com/eks-test-app:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          env:
            - name: MONGO_URL
           #   value: mongodb://mongo:27017/dev
              value: "mongodb://mongo-0.mongo:27017/dev"

#mongodb://mongodb0.example.com:27017,mongodb1.example.com:27017,mongodb2.example.com:27017/?replicaSet=myRepl
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: knote
spec:
  selector:
    app: knote
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30002
  type: LoadBalancer

